apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hermes-agent

resources:
- ../../base
- route.yaml
- secrets.yaml
- ingress.yaml

patches:
- path: deployment-patch.yaml
- path: vertex-patch.yaml

images:
- name: docker.io/nousresearch/hermes-agent
  newName: quay.io/shanemcd/hermes-agent
  newTag: vertex-55742
