FROM registry.fedoraproject.org/fedora:44 AS builder

RUN dnf install -y libguestfs-tools-c qemu-img guestfs-tools curl && dnf clean all

RUN curl -L -o /tmp/fedora-cloud.qcow2 \
    "https://download.fedoraproject.org/pub/fedora/linux/releases/42/Cloud/x86_64/images/Fedora-Cloud-Base-Generic-42-1.1.x86_64.qcow2"

COPY openshell-sandbox /tmp/openshell-sandbox

# Bundle CLI tools to inject into the image
RUN mkdir -p /tmp/tools/bin && \
    curl -sL https://github.com/cli/cli/releases/download/v2.96.0/gh_2.96.0_linux_amd64.tar.gz | \
      tar xz -C /tmp/tools --strip-components=1 && \
    curl -sL https://gitlab.com/api/v4/projects/gitlab-org%2Fcli/packages/generic/glab/1.107.0/glab_1.107.0_linux_amd64.tar.gz | \
      tar xz -C /tmp/tools/bin bin/glab --strip-components=1 && \
    curl -sL https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux-amd64-rhel8.tar.gz | \
      tar xz -C /tmp/tools/bin oc kubectl

RUN export LIBGUESTFS_BACKEND=direct && \
    qemu-img resize /tmp/fedora-cloud.qcow2 20G && \
    virt-customize -a /tmp/fedora-cloud.qcow2 \
        --install cloud-init,cloud-utils-growpart,iproute,nftables,util-linux-core \
        --install openssh-server,openssh-clients,git,curl,wget,procps-ng \
        --install python3,python3-pip,nodejs,npm,pandoc \
        --install gcc,gcc-c++,make,pkg-config,openssl-devel,protobuf-compiler \
        --install clang-devel,clang,cmake,z3-devel \
        --mkdir /opt/openshell/bin \
        --mkdir /etc/openshell \
        --mkdir /etc/openshell-tls/client \
        --mkdir /sandbox \
        --upload /tmp/openshell-sandbox:/opt/openshell/bin/openshell-sandbox \
        --chmod 0755:/opt/openshell/bin/openshell-sandbox \
        --link /opt/openshell/bin/openshell-sandbox:/openshell-sandbox \
        --upload /tmp/tools/bin/gh:/usr/local/bin/gh \
        --chmod 0755:/usr/local/bin/gh \
        --upload /tmp/tools/bin/glab:/usr/local/bin/glab \
        --chmod 0755:/usr/local/bin/glab \
        --upload /tmp/tools/bin/oc:/usr/local/bin/oc \
        --chmod 0755:/usr/local/bin/oc \
        --upload /tmp/tools/bin/kubectl:/usr/local/bin/kubectl \
        --chmod 0755:/usr/local/bin/kubectl \
        --run-command 'groupadd -g 10001 sandbox || true' \
        --run-command 'useradd -u 10001 -g 10001 -m -d /sandbox -s /bin/bash sandbox || true' \
        --run-command 'chown 10001:10001 /sandbox' \
        --run-command 'pip3 install hermes-agent' \
        --run-command 'pip3 install "jirahhh @ git+https://github.com/shanemcd/jirahhh.git"' \
        --run-command 'npm install -g @googleworkspace/cli' \
        --run-command 'curl --proto =https --tlsv1.2 -sSf https://sh.rustup.rs | CARGO_HOME=/opt/rust/cargo RUSTUP_HOME=/opt/rust/rustup sh -s -- -y --default-toolchain stable' \
        --run-command 'chmod -R a+rX /opt/rust' \
        --run-command 'ssh-keygen -A' \
        --run-command 'systemctl enable sshd' \
        --selinux-relabel

FROM scratch
COPY --from=builder /tmp/fedora-cloud.qcow2 /disk/fedora.qcow2
