FROM registry.fedoraproject.org/fedora:44 AS builder

RUN dnf install -y libguestfs-tools-c qemu-img guestfs-tools curl && dnf clean all

RUN curl -L -o /tmp/fedora-cloud.qcow2 \
    "https://download.fedoraproject.org/pub/fedora/linux/releases/42/Cloud/x86_64/images/Fedora-Cloud-Base-Generic-42-1.1.x86_64.qcow2"

COPY openshell-sandbox /tmp/openshell-sandbox

RUN export LIBGUESTFS_BACKEND=direct && \
    qemu-img resize /tmp/fedora-cloud.qcow2 10G && \
    virt-customize -a /tmp/fedora-cloud.qcow2 \
        --install cloud-init,cloud-utils-growpart,openssh-server,openssh-clients,iproute,nftables \
        --mkdir /opt/openshell/bin \
        --mkdir /etc/openshell \
        --mkdir /etc/openshell-tls/client \
        --mkdir /sandbox \
        --upload /tmp/openshell-sandbox:/opt/openshell/bin/openshell-sandbox \
        --chmod 0755:/opt/openshell/bin/openshell-sandbox \
        --link /opt/openshell/bin/openshell-sandbox:/openshell-sandbox \
        --run-command 'groupadd -g 10001 sandbox || true' \
        --run-command 'useradd -u 10001 -g 10001 -m -d /sandbox -s /bin/bash sandbox || true' \
        --run-command 'chown 10001:10001 /sandbox' \
        --run-command 'ssh-keygen -A' \
        --run-command 'systemctl enable sshd' \
        --selinux-relabel

FROM scratch
COPY --from=builder /tmp/fedora-cloud.qcow2 /disk/fedora.qcow2
